'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.42.
'
Namespace WSSelex.Selex

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Web.Services.WebServiceBindingAttribute(Name:="SelexSoap", [Namespace]:="http://localhost:21479/Selex")> _
    Partial Public Class SelexProxy
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Private GetSelexOperationCompleted As System.Threading.SendOrPostCallback

        '''<remarks/>
        Public Sub New()
            MyBase.New()
            Me.Url = "http://localhost:21479/Selex.asmx"
        End Sub

        '''<remarks/>
        Public Event GetSelexCompleted As GetSelexCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://localhost:21479/Selex/GetSelex", RequestNamespace:="http://localhost:21479/Selex", ResponseNamespace:="http://localhost:21479/Selex", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function GetSelex(ByVal richiesta As String) As String
            Dim results() As Object = Me.Invoke("GetSelex", New Object() {richiesta})
            Return CType(results(0), String)
        End Function

        '''<remarks/>
        Public Function BeginGetSelex(ByVal richiesta As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetSelex", New Object() {richiesta}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndGetSelex(ByVal asyncResult As System.IAsyncResult) As Double
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), String)
        End Function

        '''<remarks/>
        Public Overloads Sub GetSelexAsync(ByVal richiesta As String)
            Me.GetSelexAsync(richiesta, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub GetSelexAsync(ByVal richiesta As String, ByVal userState As Object)
            If (Me.GetSelexOperationCompleted Is Nothing) Then
                Me.GetSelexOperationCompleted = AddressOf Me.OnGetSelexOperationCompleted
            End If
            Me.InvokeAsync("GetSelex", New Object() {richiesta}, Me.GetSelexOperationCompleted, userState)
        End Sub

        Private Sub OnGetSelexOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetSelexCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetSelexCompleted(Me, New GetSelexCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")> _
    Public Delegate Sub GetSelexCompletedEventHandler(ByVal sender As Object, ByVal e As GetSelexCompletedEventArgs)

    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code")> _
    Partial Public Class GetSelexCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs

        Private results() As Object

        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub

        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary()
                Return CType(Me.results(0), String)
            End Get
        End Property
    End Class
End Namespace
